version: '2'
services:
    web:
      build: .
      ports:
       - 4000:4000
      restart: always
      links:
       - db
    db:
      hostname: mysqlserver
      image: mysql
      ports:
        - 3307:3307
      volumes:
        - /var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: bhavika
         MYSQL_DATABASE: mydb_assignment1